#1. Profile Configuration
spring.profiles.include=prod, secret

#2. Common Project Settings
spring.application.name=pickmeal

#3. Encoding Settings
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

#4. Default Path Settings
spring.mvc.static-path-pattern=/static/**